# Generated by Django 5.1 on 2024-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=200)),
                ('Produto', models.TextField()),
                ('Dados_Complementares', models.TextField()),
                ('UM', models.CharField(max_length=200)),
                ('Categoria', models.TextField()),
            ],
        ),
    ]
