# Generated by Django 5.1 on 2025-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('un_135', models.IntegerField(blank=True, null=True)),
                ('un_136', models.IntegerField(blank=True, null=True)),
                ('un_137', models.IntegerField(blank=True, null=True)),
                ('un_138', models.IntegerField(blank=True, null=True)),
                ('uniformes', models.IntegerField(blank=True, null=True)),
                ('vol_unif', models.IntegerField(blank=True, null=True)),
                ('cam_bone', models.IntegerField(blank=True, null=True)),
                ('vol_cb', models.IntegerField(blank=True, null=True)),
                ('vol', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=20, null=True)),
                ('emite_nf', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
