# Generated by Django 5.1 on 2024-08-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='SKU',
            field=models.IntegerField(),
        ),
    ]
