# Generated by Django 5.1 on 2025-06-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_vol_produto_vol_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='vol_total',
            new_name='vol',
        ),
    ]
