# Generated by Django 5.1 on 2025-06-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_vol_total_produto_vol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='un_135',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='un_136',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='un_137',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='un_138',
        ),
        migrations.AddField(
            model_name='produto',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='endereco1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
